# Generated by Django 4.2.1 on 2023-06-09 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_usernews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usernews',
            name='parsed_news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
        migrations.AlterField(
            model_name='usernews',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
