# Generated by Django 4.2.1 on 2023-06-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_title_alter_usernews_parsed_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
