# Generated by Django 4.2.1 on 2023-06-09 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNews',
        ),
    ]
