# Generated by Django 4.2.1 on 2023-06-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_moderated_news_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='moderated',
        ),
        migrations.RemoveField(
            model_name='news',
            name='moderator',
        ),
    ]
