# Generated by Django 4.2.1 on 2023-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
