# Generated by Django 4.2.1 on 2023-06-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_usernotification_is_read_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
