# Generated by Django 4.2.1 on 2023-06-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_news_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
    ]
