# Generated by Django 4.2.1 on 2023-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_remove_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernews',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
