# Generated by Django 4.2.1 on 2023-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_usernews_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernews',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_news_images/'),
        ),
    ]
