version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celeryworker
      - celerybeat

  db:
    image: postgres
    environment:
      - POSTGRES_DB=dip_news_v1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest

  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A news_aggregator worker --loglevel=info

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A news_aggregator beat --loglevel=info
